#!/usr/bin/env node
/**
 * 由 data/ 生成 README.md（中文，默认）与 README.en.md（英文），并导出 data/tools.csv。
 *
 * 环境变量：
 *   SITE      站点地址，默认 https://topxai.cn
 *   LINK_MODE 工具主链接指向哪里。
 *             "detail"   = 名称链接到站点详情页（默认，为站点引流）
 *             "official" = 名称链接到官方站点，详情页作为次要链接
 *
 * 用法：node scripts/build-readme.mjs
 */

import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SITE = (process.env.SITE || "https://topxai.cn").replace(/\/$/, "");
const LINK_MODE = process.env.LINK_MODE || "detail";
const TOP_N = 20;

const REPO = process.env.REPO || "clawhome/awesome-ai-toolbox";

/**
 * 复刻 GitHub 的标题锚点算法。
 * 注意：GitHub 是把「去掉标点后剩下的每个空格」逐个替换成 `-`，不做折叠，
 * 所以 "Text Generation & Editing" 的锚点是 `text-generation--editing`（双连字符）。
 */
const slugify = (text) =>
  text
    .toLowerCase()
    .trim()
    .replace(/[\u2000-\u206F\u2E00-\u2E7F\\'!"#$%&()*+,./:;<=>?@[\]^`{|}~]/g, "")
    .replace(/ /g, "-");

const LOCALES = {
  zh: {
    file: "README.md",
    otherFile: "README.en.md",
    otherLabel: "English",
    selfLabel: "简体中文",
    h1: "Awesome AI Toolbox · 中文 AI 工具精选",
    tagline: (n, c) => `收录 ${n} 个 AI 工具，覆盖 ${c} 个类目 · 在线浏览 👉 [topxai.cn](${SITE})`,
    toc: "目录",
    back: "↑ 返回目录",
    groups: { create: "生成创作", analyze: "分析处理", industry: "行业场景" },
    popular: "热门工具 Top 20",
    popularNote: "按站点月访问量排序，每月自动更新。",
    about: "关于本仓库",
    aboutText: [
      `本仓库是 [topxai.cn](${SITE}) 的开源镜像，把站内收录的 AI 工具整理成一份可以直接阅读、也可以被程序消费的清单。`,
      "",
      "- **中文优先**：默认中文内容，同时提供 [English](./README.en.md) 版本。",
      "- **自动同步**：每天由 GitHub Actions 从站点接口拉取最新数据并重新生成本文件，无需人工维护。",
      "- **结构化数据**：除本文件外，`data/` 目录提供 JSON 与 CSV 两种格式，可直接用于自己的项目。",
    ],
    data: "数据文件",
    dataTable: [
      ["文件", "说明"],
      ["[`data/tools.json`](./data/tools.json)", "全部工具的结构化数据（含中英名称与描述、类目、标签、官方链接）"],
      ["[`data/categories.json`](./data/categories.json)", "类目定义与分类分组"],
      ["[`data/tools.csv`](./data/tools.csv)", "同一份数据的表格版，方便用 Excel 打开"],
    ],
    contribute: "参与贡献",
    contributeText: [
      "发现遗漏的好工具，或想修正某个条目的描述？欢迎提交 Issue 或 Pull Request。",
      "",
      `收录标准与提交方式见 [CONTRIBUTING.md](./CONTRIBUTING.md)。`,
    ],
    license: "许可协议",
    licenseText: "清单内容采用 [CC0 1.0](./LICENSE) 公共领域贡献协议，可自由复制、修改与再分发；构建脚本同样以 CC0 1.0 发布。",
    countLabel: "收录",
    footer: `本文件由 [\`scripts/build-readme.mjs\`](./scripts/build-readme.mjs) 自动生成，数据来源 [topxai.cn](${SITE})。`,
  },
  en: {
    file: "README.en.md",
    otherFile: "README.md",
    otherLabel: "简体中文",
    selfLabel: "English",
    h1: "Awesome AI Toolbox · Curated AI Tools",
    tagline: (n, c) => `${n} AI tools across ${c} categories · Browse online 👉 [topxai.cn](${SITE})`,
    toc: "Table of Contents",
    back: "↑ Back to top",
    groups: { create: "Create", analyze: "Analyze", industry: "Industries" },
    popular: "Top 20 popular tools",
    popularNote: "Ranked by monthly site visits, refreshed every month.",
    about: "About",
    aboutText: [
      `This repository is the open mirror of [topxai.cn](${SITE}), turning the AI tools catalogued on the site into a list that is readable by humans and consumable by programs.`,
      "",
      "- **Chinese-first**: the [简体中文](./README.md) version is the default.",
      "- **Auto-synced**: a GitHub Action pulls fresh data from the site API every day and regenerates this file.",
      "- **Structured data**: the `data/` folder ships the same content as JSON and CSV.",
    ],
    data: "Data files",
    dataTable: [
      ["File", "Description"],
      ["[`data/tools.json`](./data/tools.json)", "Structured data for every tool (bilingual name & description, category, tags, official URL)"],
      ["[`data/categories.json`](./data/categories.json)", "Category definitions and grouping"],
      ["[`data/tools.csv`](./data/tools.csv)", "The same data as a spreadsheet, easy to open in Excel"],
    ],
    contribute: "Contributing",
    contributeText: [
      "Spotted a missing tool, or a description that needs fixing? Issues and pull requests are welcome.",
      "",
      "See [CONTRIBUTING.md](./CONTRIBUTING.md) for inclusion criteria.",
    ],
    license: "License",
    licenseText: "The list content is released under [CC0 1.0](./LICENSE); the build scripts are released under the same terms.",
    countLabel: "tools",
    footer: `Generated by [\`scripts/build-readme.mjs\`](./scripts/build-readme.mjs) from [topxai.cn](${SITE}).`,
  },
};

const pick = (obj, lang) => (obj?.[lang] || "").trim();

function entryLine(tool, lang) {
  const name = pick(tool.name, lang) || pick(tool.name, "zh") || tool.slug;
  const desc = pick(tool.desc, lang) || pick(tool.desc, "zh");
  const detail = `${SITE}/ai/${tool.slug}`;
  let primary;
  let tail = "";
  if (LINK_MODE === "official" && tool.url) {
    primary = tool.url;
    tail = lang === "zh" ? ` · [详情](${detail})` : ` · [details](${detail})`;
  } else {
    primary = detail;
    if (tool.url) tail = lang === "zh" ? ` · [官网](${tool.url})` : ` · [website](${tool.url})`;
  }
  return `- **[${name}](${primary})** — ${desc}${tail}`;
}

function render(lang, tools, cats) {
  const L = LOCALES[lang];
  const visible = cats.filter((c) => tools.some((t) => t.category === c.id));
  const groups = ["create", "analyze", "industry"];
  const total = tools.length;
  const out = [];

  out.push(`[${L.otherLabel}](./${L.otherFile}) | **${L.selfLabel}**`);
  out.push("");
  out.push(`# ${L.h1}`);
  out.push("");
  out.push(`> ${L.tagline(total, visible.length)}`);
  out.push("");
  out.push(
    [
      "[![Awesome](https://awesome.re/badge.svg)](https://awesome.re)",
      `[![Stars](https://img.shields.io/github/stars/${REPO}?style=social)](https://github.com/${REPO}/stargazers)`,
      `[![Last commit](https://img.shields.io/github/last-commit/${REPO})](https://github.com/${REPO}/commits)`,
      `[![Tools](https://img.shields.io/badge/tools-${total}-blue)](#${slugify(L.toc)})`,
      "[![License: CC0-1.0](https://img.shields.io/badge/license-CC0--1.0-lightgrey)](./LICENSE)",
      `[![PRs Welcome](https://img.shields.io/badge/PRs-welcome-brightgreen)](./CONTRIBUTING.md)`,
    ].join("\n"),
  );
  out.push("");
  out.push("---");
  out.push("");

  // 目录
  out.push(`## ${L.toc}`);
  out.push("");
  for (const g of groups) {
    const inGroup = visible.filter((c) => c.group === g);
    if (!inGroup.length) continue;
    out.push(`**${L.groups[g]}**`);
    out.push("");
    for (const c of inGroup) {
      const n = tools.filter((t) => t.category === c.id).length;
      out.push(`- [${pick(c.name, lang)}](#${slugify(pick(c.name, lang))}) \`${n}\``);
    }
    out.push("");
  }
  out.push(`- [${L.popular}](#${slugify(L.popular)})`);
  out.push(`- [${L.about}](#${slugify(L.about)})`);
  out.push(`- [${L.data}](#${slugify(L.data)})`);
  out.push(`- [${L.contribute}](#${slugify(L.contribute)})`);
  out.push(`- [${L.license}](#${slugify(L.license)})`);
  out.push("");
  out.push("---");
  out.push("");

  // 分类正文
  for (const g of groups) {
    const inGroup = visible.filter((c) => c.group === g);
    if (!inGroup.length) continue;
    for (const c of inGroup) {
      const name = pick(c.name, lang);
      out.push(`## ${name}`);
      out.push("");
      out.push(`<sub>[${L.back}](#${slugify(L.toc)}) · \`${tools.filter((t) => t.category === c.id).length} ${L.countLabel}\`</sub>`);
      out.push("");
      for (const t of tools.filter((x) => x.category === c.id)) {
        out.push(entryLine(t, lang));
      }
      out.push("");
    }
  }

  out.push("---");
  out.push("");
  out.push(`## ${L.popular}`);
  out.push("");
  out.push(`<sub>${L.popularNote}</sub>`);
  out.push("");
  const popular = [...tools].filter((t) => t.visits > 0).sort((a, b) => b.visits - a.visits).slice(0, TOP_N);
  popular.forEach((t, i) => {
    const name = pick(t.name, lang) || t.slug;
    const cat = pick(cats.find((c) => c.id === t.category)?.name, lang);
    out.push(`${i + 1}. **[${name}](${SITE}/ai/${t.slug})** — ${cat}`);
  });
  out.push("");

  // 关于 / 数据 / 贡献 / 许可
  out.push(`## ${L.about}`);
  out.push("");
  out.push(...L.aboutText);
  out.push("");
  out.push(`## ${L.data}`);
  out.push("");
  out.push(`| ${L.dataTable[0][0]} | ${L.dataTable[0][1]} |`);
  out.push("| --- | --- |");
  for (const row of L.dataTable.slice(1)) out.push(`| ${row[0]} | ${row[1]} |`);
  out.push("");
  out.push(`## ${L.contribute}`);
  out.push("");
  out.push(...L.contributeText);
  out.push("");
  out.push(`## ${L.license}`);
  out.push("");
  out.push(L.licenseText);
  out.push("");
  out.push("---");
  out.push("");
  out.push(`<sub>${L.footer}</sub>`);
  out.push("");

  return out.join("\n");
}

function toCsv(tools, cats) {
  const esc = (v) => `"${String(v ?? "").replace(/"/g, '""')}"`;
  const head = ["slug", "name_zh", "name_en", "desc_zh", "desc_en", "category", "category_zh", "category_en", "url", "detail_url", "tags", "monthly_visits"];
  const lines = [head.join(",")];
  for (const t of tools) {
    const c = cats.find((x) => x.id === t.category);
    lines.push(
      [
        t.slug,
        pick(t.name, "zh"),
        pick(t.name, "en"),
        pick(t.desc, "zh"),
        pick(t.desc, "en"),
        t.category,
        pick(c?.name, "zh"),
        pick(c?.name, "en"),
        t.url,
        `${SITE}/ai/${t.slug}`,
        (t.tags || []).join(" / "),
        t.visits || "",
      ]
        .map(esc)
        .join(","),
    );
  }
  return lines.join("\n") + "\n";
}

const main = async () => {
  const [tools, cats] = await Promise.all([
    readFile(join(ROOT, "data/tools.json"), "utf8").then(JSON.parse),
    readFile(join(ROOT, "data/categories.json"), "utf8").then(JSON.parse),
  ]);

  const missingEn = tools.filter((t) => !pick(t.desc, "en")).length;

  for (const lang of ["zh", "en"]) {
    const md = render(lang, tools, cats);
    await writeFile(join(ROOT, LOCALES[lang].file), md);
    console.log(`✅ ${LOCALES[lang].file}  ${tools.length} 条  ${(md.length / 1024).toFixed(0)} KB`);
  }
  await writeFile(join(ROOT, "data/tools.csv"), toCsv(tools, cats));
  console.log(`✅ data/tools.csv`);

  if (missingEn) console.log(`\n⚠️ 有 ${missingEn} 条缺少英文描述，英文版会回退显示中文。`);
};

main().catch((err) => {
  console.error(`生成失败：${err.message}`);
  process.exit(1);
});
